wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: lightgbm
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.10.8
    start_time: 1703868716.55943
    t:
      1:
      - 1
      - 5
      - 6
      - 7
      - 8
      - 9
      - 11
      - 35
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 7
      - 8
      - 9
      - 11
      - 35
      - 41
      - 49
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.10.8
      5: 0.13.10
      6: 4.27.4
      8:
      - 5
